### ISSUE TITLE
How to auto-resize canvas within a flex item?

### ISSUE THREAD

**Issue by ffxsam** [konvajs/vue-konva#118]
This is similar to the "how do I make Kanva responsive", but it's a bit of a different issue.

This is essentially what I have:

```html
<div style="display: flex">
  <div style="flex-shrink: 0">---</div>
  <div style="flex-grow: 1" class="waveform">(Konva stage drawn here)</div>
  <div style="flex-shrink: 0">---</div>
</div>
```

The issue is, when I resize my window, the `.waveform` div shrinks accordingly since it's a flex item, but since there's a Konva div & canvas inside with a set width of (for example) 800px, the `.waveform` div won't shrink, resulting in this:

![Screenshot_2020-08-22 Tracks ReelCrafter](https://user-images.githubusercontent.com/12532733/90967364-d30f0300-e4a3-11ea-85e2-a10ab81e23f0.png)

So I can't use `stage.width()` to set the new `.waveform` `offsetWidth` because it's not actually changing. How do I make this Konva stage responsive within a flex item?

**Comment by lavrton** [comment]
I am not 100% sure what is flex behavior here. Probably it is not getting smaller, because Stage is using the space.

In a similar issue I did this:
1. add `position: relative` to the parent of the stage. `.waveform` in your case.
2. use `position: absolute; width: 100%` for stage container.
3. Update the stage size of container width.

**Comment by ffxsam** [comment]
@lavrton Exactly, the Konva div/canvas is a set width so it's preventing the flex parent from shrinking. I'll try your suggestion and report back.

**Comment by ffxsam** [comment]
@lavrton No luck. I can't override the stage container (`div.konvajs-content`) no matter what. The styles are being programmatically set. My SCSS is below.

```scss
.waveform {
  cursor: pointer;
  height: 100%;
  position: relative;
  transition: opacity 0.5s ease;

  > div.konvajs-content {
    position: absolute !important;
    width: 100% !important;
  }

  &.paused {
    filter: grayscale(100%);
    opacity: 0.7;
  }
}
```

But if I edit the HTML in Firefox Dev Tools and change the style width to 100% and position to absolute, it works perfectly.
